version: "3.7"
services:

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - mynet
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - mynet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    deploy:
      restart_policy:
        condition: on-failure
        
networks:
  mynet: